### ISSUE TITLE
No explanation for finding Counterfactual explanation for negative instances 

### ISSUE THREAD

**Issue by changingthebits** [linkedin/TE2Rules#11]
Hi,

Your [blog](https://towardsdatascience.com/te2rules-explaining-why-did-my-model-say-that-54214941075b) on Medium explains that the library module is capable of finding Counterfactual explanation for negative instances, but I could not find how your algorithm does that in your [paper](https://arxiv.org/pdf/2206.14359) or the blog as well.

Can you share how your algorithm does this? Or share the relevant documentation if any?

Thanks!

**Comment by groshanlal** [comment]
I hope you are referring to this blog: https://towardsdatascience.com/te2rules-explaining-why-did-my-model-say-that-54214941075b.

The relevant code for this blog can be found here: https://github.com/groshanlal/XGBoost-Model-Explanation-Demo/blob/main/Model%20Explanation%20Demo.ipynb

This notebook contains the code for generating the counterfactual explanations.
