### ISSUE TITLE
keyerror:0

### ISSUE THREAD

**Issue by wanglu1223** [linkedin/TE2Rules#2]
when i runing the demo code  
"from te2rules.explainer import ModelExplainer
model_explainer = ModelExplainer(model=model, feature_names=feature_names)
rules = model_explainer.explain(X=x_train, y=y_train_pred)"
cause a error"keyerror:0"

**Comment by wanglu1223** [comment]
> when i runing the demo code "from te2rules.explainer import ModelExplainer model_explainer = ModelExplainer(model=model, feature_names=feature_names) rules = model_explainer.explain(X=x_train, y=y_train_pred)" cause a error"keyerror:0"

**Comment by groshanlal** [comment]
Is this already solved?
